// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * backend service
 *
 * Сервис для управления ПВЗ и приемкой товаров
 *
 * API version: 1.0.0
 */

package dto




type LoginPostRequest struct {

	Email string `json:"email"`

	Password string `json:"password"`
}

// AssertLoginPostRequestRequired checks if the required fields are not zero-ed
func AssertLoginPostRequestRequired(obj LoginPostRequest) error {
	elements := map[string]interface{}{
		"email": obj.Email,
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertLoginPostRequestConstraints checks if the values respects the defined constraints
func AssertLoginPostRequestConstraints(obj LoginPostRequest) error {
	return nil
}
