// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * backend service
 *
 * Сервис для управления ПВЗ и приемкой товаров
 *
 * API version: 1.0.0
 */

package dto




type DummyLoginPostRequest struct {

	Role string `json:"role"`
}

// AssertDummyLoginPostRequestRequired checks if the required fields are not zero-ed
func AssertDummyLoginPostRequestRequired(obj DummyLoginPostRequest) error {
	elements := map[string]interface{}{
		"role": obj.Role,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertDummyLoginPostRequestConstraints checks if the values respects the defined constraints
func AssertDummyLoginPostRequestConstraints(obj DummyLoginPostRequest) error {
	return nil
}
