// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * backend service
 *
 * Сервис для управления ПВЗ и приемкой товаров
 *
 * API version: 1.0.0
 */

package dto


import (
	"time"
)



type Product struct {

	Id string `json:"id,omitempty"`

	DateTime time.Time `json:"dateTime,omitempty"`

	Type string `json:"type"`

	ReceptionId string `json:"receptionId"`
}

// AssertProductRequired checks if the required fields are not zero-ed
func AssertProductRequired(obj Product) error {
	elements := map[string]interface{}{
		"type": obj.Type,
		"receptionId": obj.ReceptionId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertProductConstraints checks if the values respects the defined constraints
func AssertProductConstraints(obj Product) error {
	return nil
}
