// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * backend service
 *
 * Сервис для управления ПВЗ и приемкой товаров
 *
 * API version: 1.0.0
 */

package dto




type ReceptionsPostRequest struct {

	PvzId string `json:"pvzId"`
}

// AssertReceptionsPostRequestRequired checks if the required fields are not zero-ed
func AssertReceptionsPostRequestRequired(obj ReceptionsPostRequest) error {
	elements := map[string]interface{}{
		"pvzId": obj.PvzId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertReceptionsPostRequestConstraints checks if the values respects the defined constraints
func AssertReceptionsPostRequestConstraints(obj ReceptionsPostRequest) error {
	return nil
}
