// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * backend service
 *
 * Сервис для управления ПВЗ и приемкой товаров
 *
 * API version: 1.0.0
 */

package dto




type PvzGet200ResponseInner struct {

	Pvz Pvz `json:"pvz,omitempty"`

	Receptions []PvzGet200ResponseInnerReceptionsInner `json:"receptions,omitempty"`
}

// AssertPvzGet200ResponseInnerRequired checks if the required fields are not zero-ed
func AssertPvzGet200ResponseInnerRequired(obj PvzGet200ResponseInner) error {
	if err := AssertPvzRequired(obj.Pvz); err != nil {
		return err
	}
	for _, el := range obj.Receptions {
		if err := AssertPvzGet200ResponseInnerReceptionsInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertPvzGet200ResponseInnerConstraints checks if the values respects the defined constraints
func AssertPvzGet200ResponseInnerConstraints(obj PvzGet200ResponseInner) error {
	if err := AssertPvzConstraints(obj.Pvz); err != nil {
		return err
	}
	for _, el := range obj.Receptions {
		if err := AssertPvzGet200ResponseInnerReceptionsInnerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
