configs:
  psql_init:
    file: ./config/init.sql

volumes:
    postgres:
  
networks:
  app01:
    driver: bridge

services:
  db:
    image: postgres:17.4
    restart: always
    container_name: pg_pvz
    env_file:
      - ./config/app.env
    volumes:
      - ./_postgres:/var/lib/postgresql/data/
    networks:
      - app01
    ports:
      - "25913:5432"
    configs:
      - source: psql_init
        target: /docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgre"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./config/app.env
    ports:
      - "8080:8080"
    networks:
      - app01
    command:
      - sh
      - -c
      - "./main"