services:
  postgres:
    image: postgres:17.4
    restart: always
    container_name: pg_pvz
    environment:
      POSTGRES_USER: avitopvz
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db_pvz
    volumes:
      - ./_postgres:/var/lib/postgresql/data/
    networks:
      - psql
    ports:
      - "25913:5432"
    configs:
      - source: psql_init
        target: /docker-entrypoint-initdb.d/init.sql

configs:
  psql_init:
    file: ./config/init.sql

volumes:
    postgres:
  
networks:
  psql:
    driver: bridge